// utils/words.js — HY Words Bank
// Banco global de palavras para jogos de português.
// Regra: null = atributo não aplicável a esta palavra.
// Nunca hardcode listas de palavras nos jogos — consulte window.HYWords.
window.HYWords = [

  // ── ANIMAIS ──────────────────────────────────────────────────────────────

  {
    palavra: 'GATO', tamanho: 4, minuscula: 'gato', emoji: '🐱',
    coletivo: 'GATARIA',
    sinonimos: ['FELINO', 'BICHANO'],
    oposto: null,
    rimas: ['PATO', 'RATO', 'MATO', 'FATO', 'BARATO', 'NATO', 'DATO', 'SAPATO'],
    silabas: ['GA', 'TO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'GAT', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['animais'],
  },
  {
    palavra: 'PATO', tamanho: 4, minuscula: 'pato', emoji: '🦆',
    coletivo: 'NINHADA',
    sinonimos: null,
    oposto: null,
    rimas: ['GATO', 'RATO', 'MATO', 'FATO', 'BARATO', 'NATO', 'DATO', 'SAPATO'],
    silabas: ['PA', 'TO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'P', suffix: 'TO' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['animais'],
  },
  {
    palavra: 'RATO', tamanho: 4, minuscula: 'rato', emoji: '🐭',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['GATO', 'PATO', 'MATO', 'FATO', 'BARATO', 'NATO', 'DATO', 'SAPATO'],
    silabas: ['RA', 'TO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'RAT', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'SAPO', tamanho: 4, minuscula: 'sapo', emoji: '🐸',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['SA', 'PO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'SAP', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'URSO', tamanho: 4, minuscula: 'urso', emoji: '🐻',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['UR', 'SO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'URS', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['animais'],
  },
  {
    palavra: 'VACA', tamanho: 4, minuscula: 'vaca', emoji: '🐄',
    coletivo: 'MANADA',
    sinonimos: null,
    oposto: null,
    rimas: ['FACA'],
    silabas: ['VA', 'CA'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'FOCA', tamanho: 4, minuscula: 'foca', emoji: '🦭',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['FO', 'CA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'F', suffix: 'CA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'LEÃO', tamanho: 4, minuscula: 'leão', emoji: '🦁',
    coletivo: 'ALCATEIA',
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['LE', 'ÃO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'E', prefix: 'L', suffix: 'ÃO' },
    acento: { tipo: 'til', posicao: 2, letra: 'Ã' },
    erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)', faseAcento: 3,
    categorias: ['animais'],
  },
  {
    palavra: 'ZEBRA', tamanho: 5, minuscula: 'zebra', emoji: '🦓',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['ZE', 'BRA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'E', prefix: 'Z', suffix: 'BRA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'GIRAFA', tamanho: 6, minuscula: 'girafa', emoji: '🦒',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['GI', 'RA', 'FA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'CAVALO', tamanho: 6, minuscula: 'cavalo', emoji: '🐴',
    coletivo: 'TROPILHA',
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['CA', 'VA', 'LO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'MACACO', tamanho: 6, minuscula: 'macaco', emoji: '🐒',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['BURACO', 'BARRACO', 'PALHAÇO'],
    silabas: ['MA', 'CA', 'CO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'ELEFANTE', tamanho: 8, minuscula: 'elefante', emoji: '🐘',
    coletivo: 'MANADA',
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['E', 'LE', 'FAN', 'TE'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'BORBOLETA', tamanho: 9, minuscula: 'borboleta', emoji: '🦋',
    coletivo: 'NUVEM',
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BOR', 'BO', 'LE', 'TA'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'TARTARUGA', tamanho: 9, minuscula: 'tartaruga', emoji: '🐢',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['TAR', 'TA', 'RU', 'GA'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'LAGARTO', tamanho: 7, minuscula: 'lagarto', emoji: '🦎',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['LA', 'GAR', 'TO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'PASSARINHO', tamanho: 10, minuscula: 'passarinho', emoji: '🐦',
    coletivo: 'BANDO',
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['PAS', 'SA', 'RI', 'NHO'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },

  // ── OBJETOS DO DIA A DIA ─────────────────────────────────────────────────

  {
    palavra: 'BOLA', tamanho: 4, minuscula: 'bola', emoji: '⚽',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['COLA', 'MOLA', 'GOLA', 'ESCOLA', 'PISTOLA'],
    silabas: ['BO', 'LA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'B', suffix: 'LA' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['objetos', 'esportes'],
  },
  {
    palavra: 'CASA', tamanho: 4, minuscula: 'casa', emoji: '🏠',
    coletivo: null,
    sinonimos: ['LAR'],
    oposto: null,
    rimas: null,
    silabas: ['CA', 'SA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'CAS', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['lugares'],
  },
  {
    palavra: 'MESA', tamanho: 4, minuscula: 'mesa', emoji: '🪑',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['ME', 'SA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'MES', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['objetos'],
  },
  {
    palavra: 'DADO', tamanho: 4, minuscula: 'dado', emoji: '🎲',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['DA', 'DO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'DAD', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'jogos'],
  },
  {
    palavra: 'BOLO', tamanho: 4, minuscula: 'bolo', emoji: '🎂',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BO', 'LO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'BÔL', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },
  {
    palavra: 'FACA', tamanho: 4, minuscula: 'faca', emoji: '🔪',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['VACA'],
    silabas: ['FA', 'CA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'F', suffix: 'CA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'MEIA', tamanho: 4, minuscula: 'meia', emoji: '🧦',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['MEI', 'A'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'roupas'],
  },
  {
    palavra: 'TELA', tamanho: 4, minuscula: 'tela', emoji: '📺',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['VELA', 'PANELA', 'JANELA', 'CANELA', 'ESTRELA'],
    silabas: ['TE', 'LA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'E', prefix: 'T', suffix: 'LA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'RODA', tamanho: 4, minuscula: 'roda', emoji: '⚙️',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['RO', 'DA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'R', suffix: 'DA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'BOTA', tamanho: 4, minuscula: 'bota', emoji: '👢',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BO', 'TA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'B', suffix: 'TA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'roupas'],
  },
  {
    palavra: 'LATA', tamanho: 4, minuscula: 'lata', emoji: '🥫',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['MATA', 'PATA', 'RATA'],
    silabas: ['LA', 'TA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'L', suffix: 'TA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'MALA', tamanho: 4, minuscula: 'mala', emoji: '💼',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['MA', 'LA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'M', suffix: 'LA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'COPO', tamanho: 4, minuscula: 'copo', emoji: '🥛',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['CO', 'PO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'C', suffix: 'PO' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'LIVRO', tamanho: 5, minuscula: 'livro', emoji: '📚',
    coletivo: 'BIBLIOTECA',
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['LI', 'VRO'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['objetos'],
  },
  {
    palavra: 'CARRO', tamanho: 5, minuscula: 'carro', emoji: '🚗',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['CAR', 'RO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'CARR', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['objetos', 'transporte'],
  },
  {
    palavra: 'BANCO', tamanho: 5, minuscula: 'banco', emoji: '🏦',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BAN', 'CO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'BANC', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['lugares', 'objetos'],
  },
  {
    palavra: 'NAVIO', tamanho: 5, minuscula: 'navio', emoji: '🚢',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['NA', 'VIO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'NAVI', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['transporte'],
  },
  {
    palavra: 'SAPATO', tamanho: 6, minuscula: 'sapato', emoji: '👟',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['GATO', 'PATO', 'RATO', 'MATO', 'BARATO'],
    silabas: ['SA', 'PA', 'TO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'roupas'],
  },
  {
    palavra: 'JANELA', tamanho: 6, minuscula: 'janela', emoji: '🪟',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['VELA', 'PANELA', 'CANELA', 'ESTRELA', 'TELA'],
    silabas: ['JA', 'NE', 'LA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'PANELA', tamanho: 6, minuscula: 'panela', emoji: '🍳',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['VELA', 'JANELA', 'CANELA', 'ESTRELA'],
    silabas: ['PA', 'NE', 'LA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'CANETA', tamanho: 6, minuscula: 'caneta', emoji: '🖊️',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['CA', 'NE', 'TA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'CADERNO', tamanho: 7, minuscula: 'caderno', emoji: '📓',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['CA', 'DER', 'NO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['objetos'],
  },
  {
    palavra: 'TELEFONE', tamanho: 8, minuscula: 'telefone', emoji: '📱',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['TE', 'LE', 'FO', 'NE'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'BICICLETA', tamanho: 9, minuscula: 'bicicleta', emoji: '🚲',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BI', 'CI', 'CLE', 'TA'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'transporte'],
  },
  {
    palavra: 'GELADEIRA', tamanho: 9, minuscula: 'geladeira', emoji: '🧊',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['GE', 'LA', 'DEI', 'RA'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'COMPUTADOR', tamanho: 10, minuscula: 'computador', emoji: '💻',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['COM', 'PU', 'TA', 'DOR'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },

  // ── ALIMENTOS ────────────────────────────────────────────────────────────

  {
    palavra: 'LAGO', tamanho: 4, minuscula: 'lago', emoji: '🏞️',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['LA', 'GO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'LAG', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza'],
  },
  {
    palavra: 'FOGO', tamanho: 4, minuscula: 'fogo', emoji: '🔥',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['JOGO', 'LOGO', 'AFOGO', 'DIÁLOGO'],
    silabas: ['FO', 'GO'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'FOG', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza'],
  },
  {
    palavra: 'UVA', tamanho: 3, minuscula: 'uva', emoji: '🍇',
    coletivo: 'CACHO',
    sinonimos: null,
    oposto: null,
    rimas: ['LUVA', 'CHUVA'],
    silabas: ['U', 'VA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'UV', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos', 'frutas'],
  },
  {
    palavra: 'FRUTA', tamanho: 5, minuscula: 'fruta', emoji: '🍓',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['FRU', 'TA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'FRUT', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['alimentos', 'frutas'],
  },
  {
    palavra: 'TOMATE', tamanho: 6, minuscula: 'tomate', emoji: '🍅',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['TO', 'MA', 'TE'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },
  {
    palavra: 'PIPOCA', tamanho: 6, minuscula: 'pipoca', emoji: '🍿',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['PI', 'PO', 'CA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },
  {
    palavra: 'BANANA', tamanho: 6, minuscula: 'banana', emoji: '🍌',
    coletivo: 'CACHO',
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BA', 'NA', 'NA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos', 'frutas'],
  },
  {
    palavra: 'SALADA', tamanho: 6, minuscula: 'salada', emoji: '🥗',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['SA', 'LA', 'DA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },
  {
    palavra: 'BISCOITO', tamanho: 8, minuscula: 'biscoito', emoji: '🍪',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BIS', 'COI', 'TO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },
  {
    palavra: 'MELANCIA', tamanho: 8, minuscula: 'melancia', emoji: '🍉',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['ME', 'LAN', 'CI', 'A'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos', 'frutas'],
  },
  {
    palavra: 'ABACAXI', tamanho: 7, minuscula: 'abacaxi', emoji: '🍍',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['A', 'BA', 'CA', 'XI'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos', 'frutas'],
  },
  {
    palavra: 'ABACATE', tamanho: 7, minuscula: 'abacate', emoji: '🥑',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['A', 'BA', 'CA', 'TE'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos', 'frutas'],
  },
  {
    palavra: 'CHOCOLATE', tamanho: 9, minuscula: 'chocolate', emoji: '🍫',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['CHO', 'CO', 'LA', 'TE'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },

  // ── NATUREZA / LUGARES ───────────────────────────────────────────────────

  {
    palavra: 'LUA', tamanho: 3, minuscula: 'lua', emoji: '🌙',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['RUA', 'PUA'],
    silabas: ['LU', 'A'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'U', prefix: 'L', suffix: 'A' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza', 'espaço'],
  },
  {
    palavra: 'RUA', tamanho: 3, minuscula: 'rua', emoji: '🛣️',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['LUA', 'PUA'],
    silabas: ['RU', 'A'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'U', prefix: 'R', suffix: 'A' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['lugares'],
  },
  {
    palavra: 'HORTA', tamanho: 5, minuscula: 'horta', emoji: '🥦',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['HOR', 'TA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'HORT', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza', 'lugares'],
  },
  {
    palavra: 'NOITE', tamanho: 5, minuscula: 'noite', emoji: '🌙',
    coletivo: null,
    sinonimos: null,
    oposto: 'DIA',
    rimas: null,
    silabas: ['NOI', 'TE'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'N', suffix: 'ITE' },
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'Depois da ', destaque: 'NOITE', pos: ' escura, vem o claro...', resposta: 'DIA' }],
    categorias: ['tempo'],
  },
  {
    palavra: 'VENTO', tamanho: 5, minuscula: 'vento', emoji: '💨',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['VEN', 'TO'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza'],
  },
  {
    palavra: 'TERRA', tamanho: 5, minuscula: 'terra', emoji: '🌍',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['TER', 'RA'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza', 'espaço'],
  },
  {
    palavra: 'ESCOLA', tamanho: 6, minuscula: 'escola', emoji: '🏫',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['BOLA', 'COLA', 'MOLA', 'GOLA'],
    silabas: ['ES', 'CO', 'LA'],
    dificuldade: 'medio',
    vogalFaltante: { vogal: 'A', prefix: 'ESCOL', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['lugares'],
  },
  {
    palavra: 'PRIMAVERA', tamanho: 9, minuscula: 'primavera', emoji: '🌸',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['PRI', 'MA', 'VE', 'RA'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza', 'tempo'],
  },

  // ── ADJETIVOS / ESTADOS ──────────────────────────────────────────────────

  {
    palavra: 'FELIZ', tamanho: 5, minuscula: 'feliz', emoji: '😄',
    coletivo: null,
    sinonimos: ['CONTENTE', 'ALEGRE', 'ANIMADO'],
    oposto: 'TRISTE',
    rimas: null,
    silabas: ['FE', 'LIZ'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [
      { pre: 'O cachorro ficou muito ', destaque: 'FELIZ', pos: ' com o presente.', resposta: 'CONTENTE' },
      { pre: 'A criança estava muito ', destaque: 'FELIZ', pos: ', mas depois ficou...', resposta: 'TRISTE' },
    ],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['sentimentos'],
  },
  {
    palavra: 'TRISTE', tamanho: 6, minuscula: 'triste', emoji: '😢',
    coletivo: null,
    sinonimos: ['ABATIDO', 'MELANCÓLICO'],
    oposto: 'FELIZ',
    rimas: null,
    silabas: ['TRIS', 'TE'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [
      { pre: 'O menino ficou muito ', destaque: 'TRISTE', pos: ' com a notícia.', resposta: 'ABATIDO' },
      { pre: 'O menino estava ', destaque: 'TRISTE', pos: ', mas depois ficou muito...', resposta: 'FELIZ' },
    ],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['sentimentos'],
  },
  {
    palavra: 'GRANDE', tamanho: 6, minuscula: 'grande', emoji: '🐘',
    coletivo: null,
    sinonimos: ['ENORME', 'GIGANTE'],
    oposto: 'PEQUENO',
    rimas: null,
    silabas: ['GRAN', 'DE'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [
      { pre: 'O elefante é um animal muito ', destaque: 'GRANDE', pos: ', mas a formiga é muito...', resposta: 'PEQUENO' },
    ],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'PEQUENO', tamanho: 7, minuscula: 'pequeno', emoji: '🐭',
    coletivo: null,
    sinonimos: ['MINÚSCULO', 'TINY'],
    oposto: 'GRANDE',
    rimas: null,
    silabas: ['PE', 'QUE', 'NO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O rato é muito ', destaque: 'PEQUENO', pos: ', mas o elefante é muito...', resposta: 'GRANDE' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'RÁPIDO', tamanho: 6, minuscula: 'rápido', emoji: '🐆',
    coletivo: null,
    sinonimos: ['VELOZ', 'LIGEIRO', 'ÁGIL'],
    oposto: 'LENTO',
    rimas: null,
    silabas: ['RÁ', 'PI', 'DO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: { tipo: 'agudo', posicao: 0, letra: 'Á' },
    erroComum: null, regra: null,
    frases: [
      { pre: 'O guepardo é muito ', destaque: 'RÁPIDO', pos: ', mas a tartaruga é muito...', resposta: 'LENTO' },
    ],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'LENTO', tamanho: 5, minuscula: 'lento', emoji: '🐢',
    coletivo: null,
    sinonimos: ['DEVAGAR', 'VAGAROSO'],
    oposto: 'RÁPIDO',
    rimas: null,
    silabas: ['LEN', 'TO'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'A lesma anda muito ', destaque: 'LENTA', pos: ', mas o guepardo é muito...', resposta: 'RÁPIDO' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'BONITO', tamanho: 6, minuscula: 'bonito', emoji: '🌟',
    coletivo: null,
    sinonimos: ['LINDO', 'BELO'],
    oposto: 'FEIO',
    rimas: null,
    silabas: ['BO', 'NI', 'TO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'A rosa é muito ', destaque: 'BONITA', pos: ', mas o monstro é muito...', resposta: 'FEIO' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'FORTE', tamanho: 5, minuscula: 'forte', emoji: '💪',
    coletivo: null,
    sinonimos: ['ROBUSTO', 'MUSCULOSO', 'PODEROSO'],
    oposto: 'FRACO',
    rimas: null,
    silabas: ['FOR', 'TE'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O super-herói é muito ', destaque: 'FORTE', pos: ', mas o ratinho é muito...', resposta: 'FRACO' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'QUENTE', tamanho: 6, minuscula: 'quente', emoji: '🌡️',
    coletivo: null,
    sinonimos: ['MORNO', 'TÉPIDO'],
    oposto: 'FRIO',
    rimas: null,
    silabas: ['QUEN', 'TE'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O sorvete é bem ', destaque: 'QUENTE', pos: ', e a neve é muito...', resposta: 'FRIO' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'FRIO', tamanho: 4, minuscula: 'frio', emoji: '🧊',
    coletivo: null,
    sinonimos: ['GELADO', 'CONGELADO'],
    oposto: 'QUENTE',
    rimas: null,
    silabas: ['FRI', 'O'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O sorvete é muito ', destaque: 'FRIO', pos: ', mas a sopa é muito...', resposta: 'QUENTE' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'ALTO', tamanho: 4, minuscula: 'alto', emoji: '📏',
    coletivo: null,
    sinonimos: null,
    oposto: 'BAIXO',
    rimas: null,
    silabas: ['AL', 'TO'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'A girafa é muito ', destaque: 'ALTA', pos: ', mas o coelho é muito...', resposta: 'BAIXO' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'ANTIGO', tamanho: 6, minuscula: 'antigo', emoji: '⌚',
    coletivo: null,
    sinonimos: ['VELHO', 'ARCAICO'],
    oposto: 'NOVO',
    rimas: null,
    silabas: ['AN', 'TI', 'GO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [
      { pre: 'Aquele castelo é muito ', destaque: 'ANTIGO', pos: '.', resposta: 'VELHO' },
      { pre: 'O castelo era muito ', destaque: 'ANTIGO', pos: ', mas o apartamento era muito...', resposta: 'NOVO' },
    ],
    categorias: ['adjetivos'],
  },
  {
    palavra: 'CHEIO', tamanho: 5, minuscula: 'cheio', emoji: '🪣',
    coletivo: null,
    sinonimos: ['LOTADO', 'REPLETO'],
    oposto: 'VAZIO',
    rimas: null,
    silabas: ['CHEI', 'O'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O copo estava ', destaque: 'CHEIO', pos: ' de água, mas agora está...', resposta: 'VAZIO' }],
    categorias: ['adjetivos'],
  },

  // ── VERBOS ───────────────────────────────────────────────────────────────

  {
    palavra: 'CORRER', tamanho: 6, minuscula: 'correr', emoji: '🏃',
    coletivo: null,
    sinonimos: ['APRESSAR-SE', 'CORRER'],
    oposto: 'PARAR',
    rimas: null,
    silabas: ['COR', 'RER'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O atleta decidiu ', destaque: 'CORRER', pos: ', mas quando cansou resolveu...', resposta: 'PARAR' }],
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'PULAR', tamanho: 5, minuscula: 'pular', emoji: '🦘',
    coletivo: null,
    sinonimos: ['SALTAR', 'PULAR'],
    oposto: null,
    rimas: null,
    silabas: ['PU', 'LAR'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'FALAR', tamanho: 5, minuscula: 'falar', emoji: '🗣️',
    coletivo: null,
    sinonimos: ['DIZER', 'NARRAR'],
    oposto: 'CALAR',
    rimas: null,
    silabas: ['FA', 'LAR'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'A professora pediu para ', destaque: 'FALAR', pos: ' baixinho ou para...', resposta: 'CALAR' }],
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'DORMIR', tamanho: 6, minuscula: 'dormir', emoji: '😴',
    coletivo: null,
    sinonimos: ['DESCANSAR', 'REPOUSAR'],
    oposto: 'ACORDAR',
    rimas: null,
    silabas: ['DOR', 'MIR'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'COMEÇAR', tamanho: 7, minuscula: 'começar', emoji: '🚀',
    coletivo: null,
    sinonimos: ['INICIAR'],
    oposto: 'TERMINAR',
    rimas: null,
    silabas: ['CO', 'ME', 'ÇAR'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: { tipo: 'cedilha', posicao: 2, letra: 'Ç' },
    erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },

  // ── SENTIMENTOS / CONCEITOS ──────────────────────────────────────────────

  {
    palavra: 'AMOR', tamanho: 4, minuscula: 'amor', emoji: '❤️',
    coletivo: null,
    sinonimos: ['CARINHO', 'AFETO'],
    oposto: 'ÓDIO',
    rimas: null,
    silabas: ['A', 'MOR'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },
  {
    palavra: 'PAZ', tamanho: 3, minuscula: 'paz', emoji: '☮️',
    coletivo: null,
    sinonimos: ['HARMONIA', 'TRANQUILIDADE'],
    oposto: 'GUERRA',
    rimas: null,
    silabas: ['PAZ'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },
  {
    palavra: 'CORAGEM', tamanho: 7, minuscula: 'coragem', emoji: '🦁',
    coletivo: null,
    sinonimos: ['BRAVURA', 'VALENTIA'],
    oposto: 'MEDO',
    rimas: null,
    silabas: ['CO', 'RA', 'GEM'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },
  {
    palavra: 'ALEGRIA', tamanho: 7, minuscula: 'alegria', emoji: '🎉',
    coletivo: null,
    sinonimos: ['FELICIDADE', 'CONTENTAMENTO'],
    oposto: 'TRISTEZA',
    rimas: null,
    silabas: ['A', 'LE', 'GRI', 'A'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },

  // ── RIMAS ESPECÍFICAS ────────────────────────────────────────────────────

  {
    palavra: 'VELA', tamanho: 4, minuscula: 'vela', emoji: '🕯️',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['PANELA', 'JANELA', 'CANELA', 'ESTRELA', 'TELA'],
    silabas: ['VE', 'LA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'E', prefix: 'V', suffix: 'LA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'COLA', tamanho: 4, minuscula: 'cola', emoji: '🧴',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['BOLA', 'MOLA', 'GOLA', 'ESCOLA', 'PISTOLA'],
    silabas: ['CO', 'LA'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'DEDO', tamanho: 4, minuscula: 'dedo', emoji: '🤚',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['MEDO', 'CEDO', 'SEGREDO'],
    silabas: ['DE', 'DO'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['corpo'],
  },
  {
    palavra: 'MEDO', tamanho: 4, minuscula: 'medo', emoji: '😨',
    coletivo: null,
    sinonimos: ['TERROR', 'PAVOR'],
    oposto: 'CORAGEM',
    rimas: ['DEDO', 'CEDO', 'SEGREDO'],
    silabas: ['ME', 'DO'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },
  {
    palavra: 'GALINHA', tamanho: 7, minuscula: 'galinha', emoji: '🐔',
    coletivo: 'BANDO',
    sinonimos: null,
    oposto: null,
    rimas: ['VIZINHA', 'RAINHA', 'COZINHA', 'FARINHA', 'LINHA'],
    silabas: ['GA', 'LI', 'NHA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'CANÇÃO', tamanho: 6, minuscula: 'canção', emoji: '🎵',
    coletivo: 'REPERTÓRIO',
    sinonimos: ['MÚSICA', 'MELODIA'],
    oposto: null,
    rimas: ['CORAÇÃO', 'EMOÇÃO', 'PAIXÃO', 'SOLUÇÃO', 'TRAIÇÃO'],
    silabas: ['CAN', 'ÇÃO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: { tipo: 'til', posicao: 1, letra: 'Ã' },
    erroComum: null, regra: null, frases: null,
    categorias: ['arte', 'música'],
  },
  {
    palavra: 'CORAÇÃO', tamanho: 7, minuscula: 'coração', emoji: '❤️',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['CANÇÃO', 'EMOÇÃO', 'PAIXÃO', 'SOLUÇÃO'],
    silabas: ['CO', 'RA', 'ÇÃO'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: { tipo: 'til', posicao: 2, letra: 'Ã' },
    erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)', faseAcento: 3,
    categorias: ['corpo', 'sentimentos'],
  },
  {
    palavra: 'LUVA', tamanho: 4, minuscula: 'luva', emoji: '🧤',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['UVA', 'CHUVA'],
    silabas: ['LU', 'VA'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'U', prefix: 'L', suffix: 'VA' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'roupas'],
  },
  {
    palavra: 'CHUVA', tamanho: 5, minuscula: 'chuva', emoji: '🌧️',
    coletivo: null,
    sinonimos: null,
    oposto: 'SOL',
    rimas: ['UVA', 'LUVA'],
    silabas: ['CHU', 'VA'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza'],
  },

  // ── LUGARES / PROFISSÕES / GRUPOS ────────────────────────────────────────

  {
    palavra: 'DENTE', tamanho: 5, minuscula: 'dente', emoji: '🦷',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: ['PENTE', 'FRENTE', 'GENTE'],
    silabas: ['DEN', 'TE'],
    dificuldade: 'facil',
    vogalFaltante: { vogal: 'E', prefix: 'DENT', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['corpo'],
  },
  {
    palavra: 'FESTA', tamanho: 5, minuscula: 'festa', emoji: '🎉',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['FES', 'TA'],
    dificuldade: 'facil',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['eventos'],
  },
  {
    palavra: 'BONECA', tamanho: 6, minuscula: 'boneca', emoji: '🪆',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['BO', 'NE', 'CA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'brinquedos'],
  },
  {
    palavra: 'CABANA', tamanho: 6, minuscula: 'cabana', emoji: '🛖',
    coletivo: null,
    sinonimos: null,
    oposto: null,
    rimas: null,
    silabas: ['CA', 'BA', 'NA'],
    dificuldade: 'medio',
    vogalFaltante: null,
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['lugares'],
  },
  {
    palavra: 'ESPERANÇA', tamanho: 9, minuscula: 'esperança', emoji: '🕊️',
    coletivo: null,
    sinonimos: ['OTIMISMO', 'FÉ'],
    oposto: 'DESESPERO',
    rimas: null,
    silabas: ['ES', 'PE', 'RAN', 'ÇA'],
    dificuldade: 'dificil',
    vogalFaltante: null,
    acento: { tipo: 'cedilha', posicao: 3, letra: 'Ç' },
    erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },

  // ── SINÔNIMOS / ANTÔNIMOS — expansão ─────────────────────────────────────

  {
    palavra: 'SALTO', tamanho: 5, minuscula: 'salto', emoji: '🦘',
    coletivo: null, sinonimos: ['PULO', 'BRINCO'], oposto: null,
    rimas: null, silabas: ['SAL', 'TO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['verbos'],
  },
  {
    palavra: 'CHORO', tamanho: 5, minuscula: 'choro', emoji: '😭',
    coletivo: null, sinonimos: ['PRANTO', 'LAMENTO'], oposto: 'RISO',
    rimas: null, silabas: ['CHO', 'RO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },
  {
    palavra: 'CAMINHO', tamanho: 7, minuscula: 'caminho', emoji: '🛤️',
    coletivo: null, sinonimos: ['TRILHA', 'VIA'], oposto: null,
    rimas: null, silabas: ['CA', 'MI', 'NHO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['lugares'],
  },
  {
    palavra: 'OCEANO', tamanho: 6, minuscula: 'oceano', emoji: '🌊',
    coletivo: null, sinonimos: ['MAR', 'IMENSIDÃO'], oposto: null,
    rimas: null, silabas: ['O', 'CE', 'A', 'NO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['natureza'],
  },
  {
    palavra: 'OLHAR', tamanho: 5, minuscula: 'olhar', emoji: '👀',
    coletivo: null, sinonimos: ['ENXERGAR', 'VER'], oposto: null,
    rimas: null, silabas: ['OL', 'HAR'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'CANSADO', tamanho: 7, minuscula: 'cansado', emoji: '😪',
    coletivo: null, sinonimos: ['EXAUSTO', 'FATIGADO'], oposto: 'ANIMADO',
    rimas: null, silabas: ['CAN', 'SA', 'DO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'Após a corrida, o menino ficou muito ', destaque: 'CANSADO', pos: '.', resposta: 'EXAUSTO' }],
    categorias: ['adjetivos', 'sentimentos'],
  },
  {
    palavra: 'TRABALHO', tamanho: 8, minuscula: 'trabalho', emoji: '💼',
    coletivo: null, sinonimos: ['TAREFA', 'LABOR'], oposto: 'PREGUIÇA',
    rimas: null, silabas: ['TRA', 'BA', 'LHO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'Ela terminou todo o seu ', destaque: 'TRABALHO', pos: ' na escola.', resposta: 'TAREFA' }],
    categorias: ['verbos'],
  },
  {
    palavra: 'PREGUIÇA', tamanho: 8, minuscula: 'preguiça', emoji: '😴',
    coletivo: null, sinonimos: ['MOLEZA', 'INDOLÊNCIA'], oposto: 'TRABALHO',
    rimas: null, silabas: ['PRE', 'GUI', 'ÇA'], dificuldade: 'medio',
    vogalFaltante: null, acento: { tipo: 'cedilha', posicao: 2, letra: 'Ç' },
    erroComum: null, regra: null,
    frases: [{ pre: 'O bicho-preguiça tem muita ', destaque: 'PREGUIÇA', pos: '.', resposta: 'MOLEZA' }],
    categorias: ['sentimentos', 'animais'],
  },
  {
    palavra: 'VITÓRIA', tamanho: 7, minuscula: 'vitória', emoji: '🏆',
    coletivo: null, sinonimos: ['CONQUISTA', 'TRIUNFO'], oposto: 'DERROTA',
    rimas: null, silabas: ['VI', 'TÓ', 'RIA'], dificuldade: 'medio',
    vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'Ó' },
    erroComum: null, regra: null,
    frases: [{ pre: 'O time comemorou a ', destaque: 'VITÓRIA', pos: ' com alegria.', resposta: 'CONQUISTA' }],
    categorias: ['sentimentos'],
  },
  {
    palavra: 'GORDO', tamanho: 5, minuscula: 'gordo', emoji: '🐷',
    coletivo: null, sinonimos: ['ROBUSTO', 'CORPULENTO'], oposto: 'MAGRO',
    rimas: null, silabas: ['GOR', 'DO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O urso-polar é um animal muito ', destaque: 'GORDO', pos: '.', resposta: 'ROBUSTO' }],
    categorias: ['adjetivos'],
  },
  {
    palavra: 'ESCURO', tamanho: 6, minuscula: 'escuro', emoji: '🌑',
    coletivo: null, sinonimos: ['SOMBRIO', 'TENEBROSO'], oposto: 'CLARO',
    rimas: null, silabas: ['ES', 'CU', 'RO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O quarto estava muito ', destaque: 'ESCURO', pos: ' à noite.', resposta: 'SOMBRIO' }],
    categorias: ['adjetivos'],
  },
  {
    palavra: 'SILÊNCIO', tamanho: 8, minuscula: 'silêncio', emoji: '🤫',
    coletivo: null, sinonimos: ['QUIETUDE', 'SOSSEGO'], oposto: 'BARULHO',
    rimas: null, silabas: ['SI', 'LÊN', 'CIO'], dificuldade: 'medio',
    vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 1, letra: 'Ê' },
    erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },
  {
    palavra: 'BRINCAR', tamanho: 7, minuscula: 'brincar', emoji: '🎮',
    coletivo: null, sinonimos: ['JOGAR', 'DIVERTIR'], oposto: null,
    rimas: null, silabas: ['BRIN', 'CAR'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'As crianças adoram ', destaque: 'BRINCAR', pos: ' no parque.', resposta: 'JOGAR' }],
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'ESPERTO', tamanho: 7, minuscula: 'esperto', emoji: '🧠',
    coletivo: null, sinonimos: ['INTELIGENTE', 'SAGAZ'], oposto: null,
    rimas: null, silabas: ['ES', 'PER', 'TO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O cachorro é um animal muito ', destaque: 'ESPERTO', pos: '.', resposta: 'INTELIGENTE' }],
    classe: 'QUALIDADE (ADJETIVO)',
    categorias: ['adjetivos'],
  },
  {
    palavra: 'VIAJAR', tamanho: 6, minuscula: 'viajar', emoji: '✈️',
    coletivo: null, sinonimos: ['PERCORRER', 'EXPLORAR'], oposto: null,
    rimas: null, silabas: ['VI', 'A', 'JAR'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'CONVERSA', tamanho: 8, minuscula: 'conversa', emoji: '💬',
    coletivo: null, sinonimos: ['DIÁLOGO', 'PAPO'], oposto: 'BRIGA',
    rimas: null, silabas: ['CON', 'VER', 'SA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'Os amigos tiveram uma boa ', destaque: 'CONVERSA', pos: '.', resposta: 'DIÁLOGO' }],
    categorias: ['verbos'],
  },
  {
    palavra: 'MARAVILHOSO', tamanho: 11, minuscula: 'maravilhoso', emoji: '🌟',
    coletivo: null, sinonimos: ['FANTÁSTICO', 'INCRÍVEL'], oposto: 'HORRÍVEL',
    rimas: null, silabas: ['MA', 'RA', 'VI', 'LHO', 'SO'], dificuldade: 'dificil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O pôr do sol foi ', destaque: 'MARAVILHOSO', pos: '!', resposta: 'FANTÁSTICO' }],
    categorias: ['adjetivos'],
  },
  {
    palavra: 'RICO', tamanho: 4, minuscula: 'rico', emoji: '💰',
    coletivo: null, sinonimos: ['ABASTADO', 'MILIONÁRIO'], oposto: 'POBRE',
    rimas: null, silabas: ['RI', 'CO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'CLARO', tamanho: 5, minuscula: 'claro', emoji: '☀️',
    coletivo: null, sinonimos: ['LUMINOSO', 'BRILHANTE'], oposto: 'ESCURO',
    rimas: null, silabas: ['CLA', 'RO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'JOVEM', tamanho: 5, minuscula: 'jovem', emoji: '👦',
    coletivo: null, sinonimos: ['NOVO', 'MOÇO'], oposto: 'VELHO',
    rimas: null, silabas: ['JO', 'VEM'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'VELHO', tamanho: 5, minuscula: 'velho', emoji: '👴',
    coletivo: null, sinonimos: ['IDOSO', 'ANCIÃO'], oposto: 'JOVEM',
    rimas: null, silabas: ['VE', 'LHO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'LEMBRAR', tamanho: 7, minuscula: 'lembrar', emoji: '🧠',
    coletivo: null, sinonimos: ['RECORDAR', 'REMEMORAR'], oposto: 'ESQUECER',
    rimas: null, silabas: ['LEM', 'BRAR'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },

  // ── ANTÔNIMOS — expansão ─────────────────────────────────────────────────

  {
    palavra: 'DENTRO', tamanho: 6, minuscula: 'dentro', emoji: '📦',
    coletivo: null, sinonimos: null, oposto: 'FORA',
    rimas: null, silabas: ['DEN', 'TRO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'FORA', tamanho: 4, minuscula: 'fora', emoji: '🚪',
    coletivo: null, sinonimos: null, oposto: 'DENTRO',
    rimas: null, silabas: ['FO', 'RA'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'PERTO', tamanho: 5, minuscula: 'perto', emoji: '📍',
    coletivo: null, sinonimos: null, oposto: 'LONGE',
    rimas: null, silabas: ['PER', 'TO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'LONGE', tamanho: 5, minuscula: 'longe', emoji: '🔭',
    coletivo: null, sinonimos: null, oposto: 'PERTO',
    rimas: null, silabas: ['LON', 'GE'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'SUBIR', tamanho: 5, minuscula: 'subir', emoji: '⬆️',
    coletivo: null, sinonimos: ['ASCENDER', 'ELEVAR'], oposto: 'DESCER',
    rimas: null, silabas: ['SU', 'BIR'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'DESCER', tamanho: 6, minuscula: 'descer', emoji: '⬇️',
    coletivo: null, sinonimos: null, oposto: 'SUBIR',
    rimas: null, silabas: ['DES', 'CER'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'GANHAR', tamanho: 6, minuscula: 'ganhar', emoji: '🥇',
    coletivo: null, sinonimos: ['VENCER', 'CONQUISTAR'], oposto: 'PERDER',
    rimas: null, silabas: ['GA', 'NHAR'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'PERDER', tamanho: 6, minuscula: 'perder', emoji: '😞',
    coletivo: null, sinonimos: null, oposto: 'GANHAR',
    rimas: null, silabas: ['PER', 'DER'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'AÇÃO (VERBO)',
    categorias: ['verbos'],
  },
  {
    palavra: 'CERTO', tamanho: 5, minuscula: 'certo', emoji: '✅',
    coletivo: null, sinonimos: ['CORRETO', 'EXATO'], oposto: 'ERRADO',
    rimas: null, silabas: ['CER', 'TO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },

  // ── COLETIVOS — expansão ─────────────────────────────────────────────────

  {
    palavra: 'LOBO', tamanho: 4, minuscula: 'lobo', emoji: '🐺',
    coletivo: 'ALCATEIA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['LO', 'BO'], dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'LOB', suffix: '' },
    acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'Encontramos uma ', destaque: 'BANDO DE LOBOS', pos: ' na floresta.', resposta: 'ALCATEIA' }],
    categorias: ['animais'],
  },
  {
    palavra: 'PEIXE', tamanho: 5, minuscula: 'peixe', emoji: '🐟',
    coletivo: 'CARDUME', sinonimos: null, oposto: null,
    rimas: null, silabas: ['PEI', 'XE'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'O mergulhador viu um enorme ', destaque: 'GRUPO DE PEIXES', pos: '.', resposta: 'CARDUME' }],
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['animais'],
  },
  {
    palavra: 'ABELHA', tamanho: 6, minuscula: 'abelha', emoji: '🐝',
    coletivo: 'ENXAME', sinonimos: null, oposto: null,
    rimas: null, silabas: ['A', 'BE', 'LHA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'Um ', destaque: 'GRUPO DE ABELHAS', pos: ' voou pela floresta.', resposta: 'ENXAME' }],
    categorias: ['animais'],
  },
  {
    palavra: 'FLOR', tamanho: 4, minuscula: 'flor', emoji: '🌸',
    coletivo: 'RAMALHETE', sinonimos: null, oposto: null,
    rimas: null, silabas: ['FLOR'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null,
    frases: [{ pre: 'Ela recebeu um lindo ', destaque: 'CONJUNTO DE FLORES', pos: '.', resposta: 'RAMALHETE' }],
    categorias: ['natureza'],
  },
  {
    palavra: 'CACHORRO', tamanho: 8, minuscula: 'cachorro', emoji: '🐕',
    coletivo: 'MATILHA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['CA', 'CHOR', 'RO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['animais'],
  },
  {
    palavra: 'OVELHA', tamanho: 6, minuscula: 'ovelha', emoji: '🐑',
    coletivo: 'REBANHO', sinonimos: null, oposto: null,
    rimas: null, silabas: ['O', 'VE', 'LHA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'PORCO', tamanho: 5, minuscula: 'porco', emoji: '🐷',
    coletivo: 'VARA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['POR', 'CO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'MAPA', tamanho: 4, minuscula: 'mapa', emoji: '🗺️',
    coletivo: 'ATLAS', sinonimos: null, oposto: null,
    rimas: null, silabas: ['MA', 'PA'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'FORMIGA', tamanho: 7, minuscula: 'formiga', emoji: '🐜',
    coletivo: 'FORMIGUEIRO', sinonimos: null, oposto: null,
    rimas: null, silabas: ['FOR', 'MI', 'GA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'POMBO', tamanho: 5, minuscula: 'pombo', emoji: '🕊️',
    coletivo: 'REVOADA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['POM', 'BO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'BALEIA', tamanho: 6, minuscula: 'baleia', emoji: '🐳',
    coletivo: 'BANDO', sinonimos: null, oposto: null,
    rimas: null, silabas: ['BA', 'LEI', 'A'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'COBRA', tamanho: 5, minuscula: 'cobra', emoji: '🐍',
    coletivo: 'PRAGA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['CO', 'BRA'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'BOI', tamanho: 3, minuscula: 'boi', emoji: '🐂',
    coletivo: 'BOIADA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['BOI'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'SOLDADO', tamanho: 7, minuscula: 'soldado', emoji: '⚔️',
    coletivo: 'BATALHÃO', sinonimos: null, oposto: null,
    rimas: null, silabas: ['SOL', 'DA', 'DO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['profissões'],
  },
  {
    palavra: 'ARTISTA', tamanho: 7, minuscula: 'artista', emoji: '🎭',
    coletivo: 'ELENCO', sinonimos: null, oposto: null,
    rimas: null, silabas: ['AR', 'TIS', 'TA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['profissões', 'arte'],
  },
  {
    palavra: 'ESTRELA', tamanho: 7, minuscula: 'estrela', emoji: '⭐',
    coletivo: 'CONSTELAÇÃO', sinonimos: null, oposto: null,
    rimas: ['VELA', 'TELA', 'JANELA', 'PANELA', 'CANELA'],
    silabas: ['ES', 'TRE', 'LA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza', 'espaço'],
  },
  {
    palavra: 'PLANETA', tamanho: 7, minuscula: 'planeta', emoji: '🪐',
    coletivo: 'SISTEMA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['PLA', 'NE', 'TA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza', 'espaço'],
  },
  {
    palavra: 'OVO', tamanho: 3, minuscula: 'ovo', emoji: '🥚',
    coletivo: 'POSTURA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['O', 'VO'], dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: '', suffix: 'VO' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },
  {
    palavra: 'TIGRE', tamanho: 5, minuscula: 'tigre', emoji: '🐯',
    coletivo: 'MATILHA', sinonimos: null, oposto: null,
    rimas: null, silabas: ['TI', 'GRE'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'MOSQUITO', tamanho: 8, minuscula: 'mosquito', emoji: '🦟',
    coletivo: 'NUVEM', sinonimos: null, oposto: null,
    rimas: null, silabas: ['MOS', 'QUI', 'TO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },

  // ── RIMAS — expansão ─────────────────────────────────────────────────────

  {
    palavra: 'CEDO', tamanho: 4, minuscula: 'cedo', emoji: '🌅',
    coletivo: null, sinonimos: null, oposto: 'TARDE',
    rimas: ['DEDO', 'MEDO', 'SEGREDO'],
    silabas: ['CE', 'DO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['tempo'],
  },
  {
    palavra: 'TARDE', tamanho: 5, minuscula: 'tarde', emoji: '🌇',
    coletivo: null, sinonimos: null, oposto: 'CEDO',
    rimas: null, silabas: ['TAR', 'DE'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['tempo'],
  },
  {
    palavra: 'SEGREDO', tamanho: 7, minuscula: 'segredo', emoji: '🤫',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['DEDO', 'MEDO', 'CEDO'],
    silabas: ['SE', 'GRE', 'DO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['sentimentos'],
  },
  {
    palavra: 'JOGO', tamanho: 4, minuscula: 'jogo', emoji: '🎲',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['FOGO', 'LOGO'],
    silabas: ['JO', 'GO'], dificuldade: 'facil',
    vogalFaltante: { vogal: 'O', prefix: 'JOG', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos', 'brinquedos'],
  },
  {
    palavra: 'LOGO', tamanho: 4, minuscula: 'logo', emoji: '⏩',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['FOGO', 'JOGO'],
    silabas: ['LO', 'GO'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'PUA', tamanho: 3, minuscula: 'pua', emoji: '🔧',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['LUA', 'RUA'],
    silabas: ['PU', 'A'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'VIZINHA', tamanho: 7, minuscula: 'vizinha', emoji: '🏘️',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['GALINHA', 'COZINHA', 'FARINHA', 'RAINHA', 'LINHA'],
    silabas: ['VI', 'ZI', 'NHA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['pessoas'],
  },
  {
    palavra: 'COZINHA', tamanho: 7, minuscula: 'cozinha', emoji: '🍳',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['GALINHA', 'VIZINHA', 'FARINHA', 'RAINHA', 'LINHA'],
    silabas: ['CO', 'ZI', 'NHA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['lugares'],
  },
  {
    palavra: 'MÃO', tamanho: 3, minuscula: 'mão', emoji: '✋',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['PÃO', 'AVIÃO', 'CANÇÃO', 'CORAÇÃO'],
    silabas: ['MÃO'], dificuldade: 'facil',
    vogalFaltante: null, acento: { tipo: 'til', posicao: 0, letra: 'Ã' },
    erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)', faseAcento: 3,
    categorias: ['corpo'],
  },
  {
    palavra: 'PÃO', tamanho: 3, minuscula: 'pão', emoji: '🍞',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['MÃO', 'AVIÃO', 'CANÇÃO', 'CORAÇÃO'],
    silabas: ['PÃO'], dificuldade: 'facil',
    vogalFaltante: null, acento: { tipo: 'til', posicao: 0, letra: 'Ã' },
    erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)',
    categorias: ['alimentos'],
  },
  {
    palavra: 'AVIÃO', tamanho: 5, minuscula: 'avião', emoji: '✈️',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['MÃO', 'PÃO', 'CANÇÃO', 'CORAÇÃO'],
    silabas: ['A', 'VI', 'ÃO'], dificuldade: 'facil',
    vogalFaltante: null, acento: { tipo: 'til', posicao: 2, letra: 'Ã' },
    erroComum: null, regra: null, frases: null,
    classe: 'NOME (SUBSTANTIVO)', faseAcento: 3,
    categorias: ['transporte'],
  },
  {
    palavra: 'MATA', tamanho: 4, minuscula: 'mata', emoji: '🌿',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['LATA', 'PATA'],
    silabas: ['MA', 'TA'], dificuldade: 'facil',
    vogalFaltante: { vogal: 'A', prefix: 'MAT', suffix: '' },
    acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza'],
  },
  {
    palavra: 'PATA', tamanho: 4, minuscula: 'pata', emoji: '🐾',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['LATA', 'MATA'],
    silabas: ['PA', 'TA'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['animais'],
  },
  {
    palavra: 'BURACO', tamanho: 6, minuscula: 'buraco', emoji: '🕳️',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['MACACO', 'BARRACO'],
    silabas: ['BU', 'RA', 'CO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['natureza'],
  },
  {
    palavra: 'BARRACO', tamanho: 7, minuscula: 'barraco', emoji: '🛖',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['MACACO', 'BURACO'],
    silabas: ['BAR', 'RA', 'CO'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['lugares'],
  },
  {
    palavra: 'PENTE', tamanho: 5, minuscula: 'pente', emoji: '🪮',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['DENTE', 'FRENTE', 'GENTE'],
    silabas: ['PEN', 'TE'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'FRENTE', tamanho: 6, minuscula: 'frente', emoji: '🔛',
    coletivo: null, sinonimos: null, oposto: 'COSTAS',
    rimas: ['DENTE', 'PENTE', 'GENTE'],
    silabas: ['FREN', 'TE'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['adjetivos'],
  },
  {
    palavra: 'GENTE', tamanho: 5, minuscula: 'gente', emoji: '👥',
    coletivo: null, sinonimos: ['PESSOAS', 'POVO'], oposto: null,
    rimas: ['DENTE', 'PENTE', 'FRENTE'],
    silabas: ['GEN', 'TE'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['pessoas'],
  },
  {
    palavra: 'MOLA', tamanho: 4, minuscula: 'mola', emoji: '🌀',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['BOLA', 'COLA', 'GOLA', 'ESCOLA', 'PISTOLA'],
    silabas: ['MO', 'LA'], dificuldade: 'facil',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['objetos'],
  },
  {
    palavra: 'CANELA', tamanho: 6, minuscula: 'canela', emoji: '🫙',
    coletivo: null, sinonimos: null, oposto: null,
    rimas: ['VELA', 'TELA', 'JANELA', 'PANELA', 'ESTRELA'],
    silabas: ['CA', 'NE', 'LA'], dificuldade: 'medio',
    vogalFaltante: null, acento: null, erroComum: null, regra: null, frases: null,
    categorias: ['alimentos'],
  },

  // ── PALAVRAS COM ACENTO (Fábrica de Acentos) ────────────────────────────────

  // Fase 1 — Acento Agudo
  { palavra: 'ÁGUA',   tamanho: 4, minuscula: 'água',   emoji: '💧', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['Á', 'GUA'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 1, categorias: ['natureza'] },
  { palavra: 'CAFÉ',   tamanho: 4, minuscula: 'café',   emoji: '☕', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['CA', 'FÉ'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'É' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 1, categorias: ['alimentos'] },
  { palavra: 'LÁPIS',  tamanho: 5, minuscula: 'lápis',  emoji: '✏️', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['LÁ', 'PIS'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 1, categorias: ['objetos'] },
  { palavra: 'ÓCULOS', tamanho: 6, minuscula: 'óculos', emoji: '👓', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['Ó', 'CU', 'LOS'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Ó' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 1, categorias: ['objetos'] },
  { palavra: 'BAÚ',    tamanho: 3, minuscula: 'baú',    emoji: '🧰', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['BA', 'Ú'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'Ú' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 1, categorias: ['objetos'] },

  // Fase 2 — Acento Circunflexo
  { palavra: 'ÔNIBUS',  tamanho: 6, minuscula: 'ônibus',  emoji: '🚌', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['Ô', 'NI', 'BUS'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Ô' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 2, categorias: ['transporte'] },
  { palavra: 'BEBÊ',    tamanho: 4, minuscula: 'bebê',    emoji: '👶', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['BE', 'BÊ'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 1, letra: 'Ê' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 2, categorias: ['pessoas'] },
  { palavra: 'ROBÔ',    tamanho: 4, minuscula: 'robô',    emoji: '🤖', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['RO', 'BÔ'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 1, letra: 'Ô' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 2, categorias: ['objetos'] },
  { palavra: 'TÊNIS',   tamanho: 5, minuscula: 'tênis',   emoji: '👟', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['TÊ', 'NIS'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Ê' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 2, categorias: ['objetos', 'esportes'] },
  { palavra: 'LÂMPADA', tamanho: 7, minuscula: 'lâmpada', emoji: '💡', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['LÂM', 'PA', 'DA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Â' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 2, categorias: ['objetos'] },

  // Fase 3 — Til (LEÃO, MÃO, AVIÃO, CORAÇÃO já existem acima)
  { palavra: 'MAÇÃ', tamanho: 4, minuscula: 'maçã', emoji: '🍎', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['MA', 'ÇÃ'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'til', posicao: 1, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 3, categorias: ['alimentos', 'frutas'] },

  // Fase 4 — Mistura Divertida 1
  { palavra: 'PÉ',     tamanho: 2, minuscula: 'pé',     emoji: '🦶', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['PÉ'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'É' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 4, categorias: ['corpo'] },
  { palavra: 'AVÔ',    tamanho: 3, minuscula: 'avô',    emoji: '👴', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['A', 'VÔ'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 1, letra: 'Ô' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 4, categorias: ['pessoas'] },
  { palavra: 'MÃE',    tamanho: 3, minuscula: 'mãe',    emoji: '👩', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['MÃE'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'til', posicao: 0, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 4, categorias: ['pessoas'] },
  { palavra: 'ÁRVORE', tamanho: 6, minuscula: 'árvore', emoji: '🌳', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['ÁR', 'VO', 'RE'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 4, categorias: ['natureza'] },
  { palavra: 'TRÊS',   tamanho: 4, minuscula: 'três',   emoji: '3️⃣', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['TRÊS'], dificuldade: 'facil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Ê' }, erroComum: null, regra: null, frases: null, faseAcento: 4, categorias: ['números'] },

  // Fase 5 — Mistura Divertida 2
  { palavra: 'PÁSSARO',  tamanho: 7, minuscula: 'pássaro',  emoji: '🐦', coletivo: 'BANDO', sinonimos: null, oposto: null, rimas: null, silabas: ['PÁS', 'SA', 'RO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 5, categorias: ['animais'] },
  { palavra: 'PÊSSEGO',  tamanho: 7, minuscula: 'pêssego',  emoji: '🍑', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['PÊS', 'SE', 'GO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Ê' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 5, categorias: ['alimentos', 'frutas'] },
  { palavra: 'CAMINHÃO', tamanho: 8, minuscula: 'caminhão', emoji: '🚛', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['CA', 'MI', 'NHÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 2, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 5, categorias: ['transporte'] },
  { palavra: 'RELÓGIO',  tamanho: 7, minuscula: 'relógio',  emoji: '⌚', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['RE', 'LÓ', 'GIO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'Ó' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 5, categorias: ['objetos'] },
  { palavra: 'ÍNDIO',    tamanho: 5, minuscula: 'índio',    emoji: '🏹', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['ÍN', 'DIO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Í' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 5, categorias: ['pessoas'] },

  // Fase 6
  { palavra: 'XÍCARA',  tamanho: 6, minuscula: 'xícara',  emoji: '☕', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['XÍ', 'CA', 'RA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Í' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 6, categorias: ['objetos'] },
  { palavra: 'MÁGICA',  tamanho: 6, minuscula: 'mágica',  emoji: '🪄', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['MÁ', 'GI', 'CA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 6, categorias: ['objetos'] },
  { palavra: 'BÚSSOLA', tamanho: 7, minuscula: 'bússola', emoji: '🧭', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['BÚS', 'SO', 'LA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Ú' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 6, categorias: ['objetos'] },
  { palavra: 'VULCÃO',  tamanho: 6, minuscula: 'vulcão',  emoji: '🌋', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['VUL', 'CÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 1, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 6, categorias: ['natureza'] },
  { palavra: 'PÊNALTI', tamanho: 7, minuscula: 'pênalti', emoji: '⚽', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['PÊ', 'NAL', 'TI'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Ê' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 6, categorias: ['esportes'] },

  // Fase 7
  { palavra: 'MATEMÁTICA', tamanho: 10, minuscula: 'matemática', emoji: '🧮', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['MA', 'TE', 'MÁ', 'TI', 'CA'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 2, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 7, categorias: ['educação'] },
  { palavra: 'ECOLÓGICO', tamanho: 9,  minuscula: 'ecológico', emoji: '🌱', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['E', 'CO', 'LÓ', 'GI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 2, letra: 'Ó' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 7, categorias: ['adjetivos'] },
  { palavra: 'DINÂMICO',  tamanho: 8,  minuscula: 'dinâmico',  emoji: '⚡', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['DI', 'NÂ', 'MI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 1, letra: 'Â' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 7, categorias: ['adjetivos'] },
  { palavra: 'TUBARÃO',   tamanho: 7,  minuscula: 'tubarão',   emoji: '🦈', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['TU', 'BA', 'RÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 2, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 7, categorias: ['animais'] },
  { palavra: 'FÁBRICA',   tamanho: 7,  minuscula: 'fábrica',   emoji: '🏭', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['FÁ', 'BRI', 'CA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 7, categorias: ['lugares'] },

  // Fase 8
  { palavra: 'MÉDICO',  tamanho: 6, minuscula: 'médico',  emoji: '👨‍⚕️', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['MÉ', 'DI', 'CO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'É' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 8, categorias: ['profissões'] },
  { palavra: 'PÚBLICO', tamanho: 7, minuscula: 'público', emoji: '🏟️', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['PÚ', 'BLI', 'CO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Ú' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 8, categorias: ['adjetivos'] },
  { palavra: 'MÚSICA',  tamanho: 6, minuscula: 'música',  emoji: '🎵', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['MÚ', 'SI', 'CA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Ú' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 8, categorias: ['arte', 'música'] },
  { palavra: 'FÍSICO',  tamanho: 6, minuscula: 'físico',  emoji: '🔬', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['FÍ', 'SI', 'CO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'Í' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 8, categorias: ['adjetivos'] },

  // Fase 9 — Circunflexo avançado
  { palavra: 'ÂNCORA',  tamanho: 6, minuscula: 'âncora',  emoji: '⚓', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['ÂN', 'CO', 'RA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Â' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 9, categorias: ['objetos'] },
  { palavra: 'TÔNICO',  tamanho: 6, minuscula: 'tônico',  emoji: '💊', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['TÔ', 'NI', 'CO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Ô' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 9, categorias: ['adjetivos'] },
  { palavra: 'ÊXITO',   tamanho: 5, minuscula: 'êxito',   emoji: '🏆', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['Ê', 'XI', 'TO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Ê' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 9, categorias: ['sentimentos'] },
  { palavra: 'ÂNGULO',  tamanho: 6, minuscula: 'ângulo',  emoji: '📐', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['ÂN', 'GU', 'LO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Â' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 9, categorias: ['educação'] },
  { palavra: 'CÔNCAVO', tamanho: 7, minuscula: 'côncavo', emoji: '🪨', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['CÔN', 'CA', 'VO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Ô' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 9, categorias: ['adjetivos'] },

  // Fase 10 — Til avançado
  { palavra: 'CIDADÃO', tamanho: 7, minuscula: 'cidadão', emoji: '🧑', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['CI', 'DA', 'DÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 2, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 10, categorias: ['pessoas'] },
  { palavra: 'ESTAÇÃO', tamanho: 7, minuscula: 'estação', emoji: '🚉', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['ES', 'TA', 'ÇÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 2, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 10, categorias: ['lugares', 'transporte'] },
  { palavra: 'FUNÇÃO',  tamanho: 6, minuscula: 'função',  emoji: '📊', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['FUN', 'ÇÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 1, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 10, categorias: ['educação'] },
  { palavra: 'NAÇÃO',   tamanho: 5, minuscula: 'nação',   emoji: '🏳️', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['NA', 'ÇÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 1, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 10, categorias: ['lugares'] },
  { palavra: 'PORÇÃO',  tamanho: 6, minuscula: 'porção',  emoji: '🍱', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['POR', 'ÇÃO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'til', posicao: 1, letra: 'Ã' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 10, categorias: ['alimentos'] },

  // Fase 11 — Mistura complexa
  { palavra: 'ESPÍRITO',   tamanho: 8,  minuscula: 'espírito',   emoji: '👻', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['ES', 'PÍ', 'RI', 'TO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'Í' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 11, categorias: ['sentimentos'] },
  { palavra: 'CÂMERA',     tamanho: 6,  minuscula: 'câmera',     emoji: '📷', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['CÂ', 'ME', 'RA'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 0, letra: 'Â' }, erroComum: null, regra: null, frases: null, classe: 'NOME (SUBSTANTIVO)', faseAcento: 11, categorias: ['objetos'] },
  { palavra: 'POLÍTICO',   tamanho: 8,  minuscula: 'político',   emoji: '🏛️', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['PO', 'LÍ', 'TI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'Í' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 11, categorias: ['adjetivos'] },
  { palavra: 'HISTÓRICO',  tamanho: 9,  minuscula: 'histórico',  emoji: '📜', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['HIS', 'TÓ', 'RI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'Ó' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 11, categorias: ['adjetivos'] },
  { palavra: 'TÉCNICO',    tamanho: 7,  minuscula: 'técnico',    emoji: '🔧', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['TÉC', 'NI', 'CO'], dificuldade: 'medio', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 0, letra: 'É' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 11, categorias: ['adjetivos'] },

  // Fase 12 — Desafio Master Final
  { palavra: 'CIENTÍFICO', tamanho: 10, minuscula: 'científico', emoji: '🔭', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['CI', 'EN', 'TÍ', 'FI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 2, letra: 'Í' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 12, categorias: ['adjetivos'] },
  { palavra: 'ECONÔMICO',  tamanho: 9,  minuscula: 'econômico',  emoji: '💹', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['E', 'CO', 'NÔ', 'MI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'circunflexo', posicao: 2, letra: 'Ô' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 12, categorias: ['adjetivos'] },
  { palavra: 'FANTÁSTICO', tamanho: 10, minuscula: 'fantástico', emoji: '🌟', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['FAN', 'TÁS', 'TI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 1, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 12, categorias: ['adjetivos'] },
  { palavra: 'ESPECÍFICO', tamanho: 10, minuscula: 'específico', emoji: '🎯', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['ES', 'PE', 'CÍ', 'FI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 2, letra: 'Í' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 12, categorias: ['adjetivos'] },
  { palavra: 'GEOGRÁFICO', tamanho: 10, minuscula: 'geográfico', emoji: '🗺️', coletivo: null, sinonimos: null, oposto: null, rimas: null, silabas: ['GE', 'O', 'GRÁ', 'FI', 'CO'], dificuldade: 'dificil', vogalFaltante: null, acento: { tipo: 'agudo', posicao: 2, letra: 'Á' }, erroComum: null, regra: null, frases: null, classe: 'QUALIDADE (ADJETIVO)', faseAcento: 12, categorias: ['adjetivos'] },

];
